### ISSUE TITLE
請問在ubuntu上執行infer.py出現'NoneType' object has no attribute 'num_bindings'

### ISSUE THREAD

**Issue by bruce601080102** [Monday-Leo/YOLOv7_Tensorrt#11]
已生成出yolov7_fp16.engine,但出現如下錯誤

Traceback (most recent call last):
  File "/jupyter/local/Github/sreaming/tensorrt/infer.py", line 113, in <module>
    trt_engine = TRT_engine("./yolov7_fp16.engine")
  File "/jupyter/local/Github/sreaming/tensorrt/infer.py", line 13, in __init__
    self.init_engine()
  File "/jupyter/local/Github/sreaming/tensorrt/infer.py", line 25, in init_engine
    for index in range(self.model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'

**Comment by Jorya2333** [comment]
请问解决了吗？怎么解决的，期待您的回复

**Comment by bruce601080102** [comment]
你可以參考這個專案
https://github.com/bruce601080102/yolov7_stream_rtc
